/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'
import { Route as ApiPublicDiscordRouteImport } from './routes/api/public/discord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordRoute = ApiPublicDiscordRouteImport.update({
  id: '/api/public/discord',
  path: '/api/public/discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/discord': typeof ApiPublicDiscordRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/discord' | '/api/public/tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/discord' | '/api/public/tick'
  id: '__root__' | '/' | '/api/public/discord' | '/api/public/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDiscordRoute: typeof ApiPublicDiscordRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord': {
      id: '/api/public/discord'
      path: '/api/public/discord'
      fullPath: '/api/public/discord'
      preLoaderRoute: typeof ApiPublicDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDiscordRoute: ApiPublicDiscordRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
